name: Railway Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SVC_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Railway
        run: railway up --service=${{ env.SVC_ID }}
